version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: courtly_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: courtly_dev
    ports:
      - "5432:5432"
    volumes:
      - courtly_db_data:/var/lib/postgresql/data

volumes:
  courtly_db_data:
